version: '3.9'
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: ${APP_NAME}-mongo
    env_file: .env
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "27017:27017"
    tty: true
